#include "p16F84A.inc"
__CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _CP_OFF
ORG 0x00
    
    CBLOCK 0x20
	d1
	d2
    ENDC
    
    SET_SETTINGS
	BSF STATUS, RP0 
	MOVLW b'11111'
	MOVWF PORTA
	MOVLW b'00000000'
	MOVWF PORTB
	BCF STATUS, RP0
	CLRF PORTB
	CLRF PORTA
	
    START
	BTFSC PORTA, 0
	    GOTO FIRST_ANIMATION
	;BTFSC PORTA, 1
	    ;GOTO FIRST_ANIMATION
	;BTFSC PORTA, 2
	    ;GOTO FIRST_ANIMATION
	;BTFSC PORTA, 3
	    ;GOTO FIRST_ANIMATION
	GOTO START
	    
    FIRST_ANIMATION
	COMF PORTB
	CALL DELAY_1
	GOTO START
    
    ; -------------------------------------------------------------------------
	
    DELAY_1 ; 0.2 seconds
	MOVLW	0x3F
	MOVWF	d1
	MOVLW	0x9D
	MOVWF	d2
	CALL DELAY
	RETURN
	
    DELAY_2 ; 0.1 seconds
	MOVLW	0x1F
	MOVWF	d1
	MOVLW	0x4F
	MOVWF	d2
	CALL DELAY
	RETURN
	
    DELAY
	DECFSZ	d1, F
	GOTO	$+2
	DECFSZ	d2, F
	GOTO	DELAY
	RETURN

    END