#include "p16F84A.inc"
__CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _CP_OFF
ORG 0x00
    
    CBLOCK 0x20
	d1
	d2
    ENDC
    
    SET_SETTINGS
	BSF STATUS, RP0 
	MOVLW b'11111'
	MOVWF PORTA
	MOVLW b'00000000'
	MOVWF PORTB
	BCF STATUS, RP0
	CLRF PORTB
	CLRF PORTA
	
    START
	BTFSC PORTA, 0
	    GOTO FIRST_ANIMATION
	BTFSC PORTA, 1
	    GOTO SECOND_ANIMATION
	;BTFSC PORTA, 2
	    ;GOTO FIRST_ANIMATION
	;BTFSC PORTA, 3
	    ;GOTO FIRST_ANIMATION
	GOTO START
	    
    FIRST_ANIMATION
	CALL DELAY_2
	MOVLW b'11111111'
	MOVWF PORTB
	CALL DELAY_2
	CLRF PORTB
	GOTO START
	
    SECOND_ANIMATION
	MOVLW b'10000000'
	MOVWF PORTB
	GOTO BUCLE_INC_SECOND_ANIMATION
    
    BUCLE_INC_SECOND_ANIMATION
	BTFSC PORTB, 0
	    GOTO BUCLE_DEC_SECOND_ANIMATION
	RRF PORTB, 1
	CALL DELAY_3
	GOTO BUCLE_INC_SECOND_ANIMATION
	
    BUCLE_DEC_SECOND_ANIMATION
	BTFSC PORTB, 7
	    GOTO START
	RLF PORTB, 1
	CALL DELAY_3
	GOTO BUCLE_DEC_SECOND_ANIMATION
	
    ; -------------------------------------------------------------------------
	
    DELAY_1 ; 0.2 seconds
	MOVLW	0x3F
	MOVWF	d1
	MOVLW	0x9D
	MOVWF	d2
	CALL DELAY
	RETURN
	
    DELAY_2 ; 0.1 seconds
	MOVLW	0x1F
	MOVWF	d1
	MOVLW	0x4F
	MOVWF	d2
	CALL DELAY
	RETURN
	
    DELAY_3 ; 0.01 seconds
	MOVLW	0xCF
	MOVWF	d1
	MOVLW	0x08
	MOVWF	d2
	CALL DELAY
	RETURN
    
    DELAY
	DECFSZ	d1, F
	GOTO	$+2
	DECFSZ	d2, F
	GOTO	DELAY
	RETURN

    END